/*
 * This source file was generated by the Gradle 'init' task
 */
package dev.torcor

import dev.torcor.aoc.client.AocClient
import kotlinx.coroutines.runBlocking

fun main() = runBlocking {
    val client = AocClient()

    println(client.input("1"))
}
